# Generated by Django 5.0.6 on 2024-05-19 19:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0002_alter_wallet_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=18, default=Decimal("0.00"), max_digits=65
            ),
        ),
    ]
