# Generated by Django 5.0.6 on 2024-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=18, max_digits=65),
        ),
    ]
